version: '3.9'

services:

  # cluster control-plane
  master:
    container_name: master
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
    volumes:
      - ./master:/etc/seaweedfs

  # storage nodes
  volume:
    container_name: volume
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325'
    depends_on:
      - master

  # filesystem frontend
  filer:
    container_name: filer
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume

  # remote sync to cloud
  # filersync:
  #   container_name: filersync
  #   image: chrislusf/seaweedfs
  #   ports:
  #     - 8333:8333
  #   command: 'filer.remote.sync -dir=/buckets/bob/seaweed-cloud -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327'
  #   depends_on:
  #     - master
  #     - volume
  #     - filer

  # s3 frontend
  s3:
    container_name: s3
    image: chrislusf/seaweedfs
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9328'
    depends_on:
      - master
      - volume
      - filer

  # webdav frontend
  webdav:
    container_name: webdav
    image: chrislusf/seaweedfs
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer

  # metrics
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
